host = "coconutvtf.mysql.pythonanywhere-services.com"
port = 3306
user = "coconutvtf"
password = "Cizomo4303"
database = "coconutvtf$default"
ssh_username = "coconutvtf"
ssh_password = "drce94NU"
remote_bind_address = "coconutvtf.mysql.pythonanywhere-services.com"

PASSWORD-0 = "kaltiremexico2025*"